### ISSUE TITLE
[Question] Emit typescript interface

### ISSUE THREAD

**Issue by dcworldwide** [i18next/i18next-parser#127]
- Is this a bug or a feature request? Question
- What version are you running (`0.x` or `1.x`)? 1.x 
- Which runner (cli, gulp...)?
cli

## What I'm trying to do?
Any thoughts on how I could leverage il8next-parser to emit a typescript interface for every namespace? 

#E.g. 
I want to run this tool to produce a series of translations... i.e. en.nsA.json, en.nsB.json, es.nsA.json, es.nsB.json

For each emitted file, i want to generate a typescript interface. These interfaces will be used to strongly type my t() and <Trans /> code.

**Comment by karellm** [comment]
I'm not familiar with TS and what you seem to need is an event for every namespace file being written. You could probably write a transform that you pipe after the Parser depending on what your setup looks like. Another option is to emit an event on write. I would merge a PR supporting this.

**Comment by dcworldwide** [comment]
I think the later option, emitting an event on write would be simpler and more in-line with the existing implementation?

I'm fine to submit a PR for this. Before I do that though, I just want to make sure what I am trying to do will be supported overall by this lib.

Basically, I want to emit a TS interface from my the translation files emitted from il8n-parser. Where each property in the interface will include the translation text as a comment. This means that I can then use the TS interface to define keys in my TSX files and benefit from VS Code intellisense - removing the need for me to 1, ensure I've typed keys correctly and 2, avoid the need to have translation files open when reading my TSX files. 

A example in code:

# en.translation.json

```
SomeKey="Pozdrav iz Hrvatske"
SomeKey2="lorem..."
```

# Translation interface

```
export default interface EnTranslation {

    /*
        Pozdrav iz Hrvatske
    */
    SomeKey: string 

    /*
```
        lorem...
    */
    SomeKey2: string 
}

# tsx file 

```
import Keys from './EnTranslation'

render() {  
    return <div>
        <div>t(Keys.SomeKey)</div>
        Trans key={Keys.SomeKey} />
    </div>
}
```

**Comment by dcworldwide** [comment]
@karellm I've answered my own question. 

t() only extracts keys correctly if the first argument is a string literal. 

So...  t(Keys.SomeKey), where Keys is an enum or object or t(SomeKey) where SomeKey is a variable does not extract keys,

Can this be fixed?

**Comment by karellm** [comment]
As I said, I'm not familiar with TS and Interfaces so I'll answer to the best of my understanding.

This library doesn't parse variables on purpose, it actually should throw a warning via the event `warning:variable`. The reason is pretty obvious, the variable name doesn't necessarily match the actual key. To address this situation, I advice people to have a file somewhere with all the keys covered by the variable, or have them as a comment above the variable call. Something like:

```js
// t('option1')
// t('option2')
t(variable)
```

What you are trying to do seems pretty interesting but I'm really not sure how to address it. It would need to match the variable against the comment in the interface. I personally have no time to work on this and I'm not even sure I'd want this inside of the library since it would be very specific to your use case (or TS). If you want to sketch some implementation note, I will definitely review them though.

**Comment by dcworldwide** [comment]
You can ignore the whole ts part of my question, that was just for background. 

> This library doesn't parse variables

I may have to fork this lib to achieve this. Is it even possible with acorn to resolve a string variable?

**Comment by karellm** [comment]
I'm sure it is possible but you'll have to do your own investigation. If you fork and find that the code make sense, I'll be happy to look at a PR

**Comment by dcworldwide** [comment]
Closing.

FYI. Acorn can't resolve variables so I'm going to look to write my own solution for this.
