### ISSUE TITLE
Doesn't handle context via { context: 'male' }

### ISSUE THREAD

**Issue by birdy-** [i18next/i18next-parser#46]
We are trying to keep our translations in "real" english to have a acceptable fallback if a string isn't translated (`Do you want to continue ?` looks better than `modal.question.continue` when the string is not available in your language at the moment).
i18next doesn't handle `i18n.t('From', { context: 'date' })` but `i18n.t('From::date')`. It's an issue when you rely on key for fallback.
I quickly look at the code, and it seems we don't get any options atm.

**Comment by jamuhl** [comment]
should work...like http://i18next.com/translate/keyBasedFallback/

**Comment by birdy-** [comment]
It seems context is not stripped from the "key" if the key includes context directly :
```
i18next.t('My key', { context: 'mycontext' }); // output 'My key'
i18next.t('My key::mycontext'); // output 'My key::mycontext'
```

**Comment by jamuhl** [comment]
did you change the context seperator? Else it should be `i18next.t('My key_mycontext')`

**Comment by karellm** [comment]
First of all, I'm maintaining this project because there are a lot of users but I'm not building new features. Basically if you write a PR, I will merge it but can't put development time at the moment.

@birdy- The way the parser work, it should prepopulate other language with the default translation of your first locale (see https://github.com/i18next/i18next-parser/issues/43). This might address your concern. I personally think you should never use actual english because if you change the text for whatever reason (typo and a change of mind), it will be painful to consolidate.

As to matching `keyBasedFallback`, I agree that the parser should match `i18n` options as closely as possible. 

Finally for the context issue, as @jamuhl puts it, the default separator is `_` and not `::`. There is not option to change it but could be added pretty easily if you want to tackle it.

**Comment by birdy-** [comment]
The problem isn't the ctxSeparator (it could be `:` or `_` or `d-.-b` for some fun). It's just a missing feature which could be very useful in my case.
I totally understand it would be some work to handle this since we don't parse options atm. I posted this issue mainly to see if I get some :+1:. I'll try to push a PR this week.

**Comment by birdy-** [comment]
Done in the PR above.
