### ISSUE TITLE
Templated strings not parsed

### ISSUE THREAD

**Issue by coyotte508** [i18next/i18next-parser#83]
Version: **1.0.0-beta-6**

I'm not sure if this is a bug (not handling all quote formats) or a feature (handling new quote format).

This gets parsed properly:

```js
t('Hello world')
```

Neither of those gets parsed:

```js
t(`Hello world`)
t(`Hello ${name}`)
```

Config file:

```json
{
  "keySeparator": "__NO_KEY_SEPARATOR__",
  "namespaceSeparator": "|",
  "lexers": {
    "js": ["JavascriptLexer", "JsxLexer"]
  },
  "reactNamespace": true,
  "sort": true,
  "locales": ["en", "fr"]
}
```

Usage through cli.

**Comment by karellm** [comment]
It is a feature. There is NO valid reason to use &#96; instead of ' or " for a string that doesn't actually interpolate. And if there is interpolation, then it is not supported by this library. The reason is that if we extract `Hello ${name}` as a key, it won't work at runtime, since at run time it will look for `Hello John` for instance, which won't exist in the catalog.

If you need variables in keys, I recommend that you use a comment to list possible values:

```js
// All possible values for ${name}
// t('Hello John')
// t('Hello Sarah')
// ...
```

And if what you need is i18next interpolation, you should NOT use &#96; but regular string with ' or ".

**Comment by ramiel** [comment]
Backticks are not used for interpolation only, but also to have new lines in the text. Interpolation is not supported regardless of the quotes used (you posted an example of interpolation with normal quotes). I think this should be reviewed

**Comment by vincaslt** [comment]
Is is a case where you can't use `<Trans>` component?

**Comment by ramiel** [comment]
No, I'm talking about `t` functions

**Comment by ramiel** [comment]
Oh sorry, I wouldn't make any assumption on what and why a user can or cannot use one of the available tools, there will always be a case for something. Also, i18next can be used outside of react projects where you only have the translation function, not the component

**Comment by karellm** [comment]
@ramiel You have a valid point about multi line strings. Are you willing to make a PR for this?

**Comment by ramiel** [comment]
Not at the moment, I'm pretty busy. In case I can in the next weeks, any hint at where to look?

**Comment by bsor-dev** [comment]
Got same issue, any work around?
